#import "@THR/Sum:1.0.0": *
#show: template

#let subset = $subset.eq$
#let Id = math.op("Id")
#let Ker = math.op("Ker")
#let Im = math.op("Im")
#let Irr = math.op("Irr")
#let iso = $tilde.equiv$
#let char = math.op("Char")

#sect("Tutorial Series 1: Remainders", level: 1)
#exr[
  Consider the ring of polynomials $ZZ[X]$ with indeterminate $X$.
]
#qst[Show that $ZZ[X]\/(X) tilde.equiv ZZ$.]
Take the map $phi: ZZ[X] -> ZZ$ such that $phi(a_0 + a_1 X + dots + a_n X^n) = a_0$, $phi$ is a ring homomorphism with $Ker phi = (X)$ and $Im phi = ZZ$ then by the first isomorphism theorem $ZZ[X]\/(X) tilde.equiv ZZ$.

#qst[Show that $(2)+(x)$ is not generated by a singleton.]
Suppose there exists $P in ZZ[X]$ such that $(P) = (2) + (X)$, since $2 in (2) + (X)$ then $2 in (P)$ so $2 = P Q$ with $Q in ZZ[X]$ but that means that $deg(P) + deg(Q) = 0 => deg P = 0$ so $P = p in ZZ$, since $2 in (p)$ then $p | 2 => p = plus.minus 1$ or $p = plus.minus 2$ which are both impossible since $1 in ZZ[X] \\ ((2) + (X))$ and $2+X in (2) + (X) \\ (2)$.

#qst[Deduce that $ZZ[X]$ is not a PID.]
- From 1.1.1 we have that $ZZ[X]$ is a PID and $X$ is irreducible then $(X)$ is a maximal ideal so $ZZ[X]\/(X)$ is a field but $ZZ[X]\/(X) tilde.equiv ZZ$ which means that $ZZ$ is a field, contradiction.
- From 1.1.2 we have that $(2) + (x)$ is an ideal of $ZZ[X]$ but it is not a principle ideal.

#qst[Is $ZZ[X]$ a Euclidean domain ?]
$ZZ[X]$ is not a Euclidean domain since it is not a PID.

#exr[
  Find embeddings and automorphisms in the following cases.
]

#qst[
  $K=QQ(sqrt(2)), QQ(root(4, 2)), QQ(root(3, 5))$ and $L=CC$.
]

- $K = QQ(sqrt(2))$: we have that $Irr(sqrt(2), K, X)=X^2-2$ since it is a monic $2$-Eisenstein that nullifies $sqrt(2)$ and we have that $char QQ = 0$ and $[QQ(sqrt(2)):QQ]=2$ so there are only two embeddings
$
  sigma_1&: sqrt(2) |-> sqrt(2)\
  sigma_2&: sqrt(2) |-> -sqrt(2)
$
which are both automorphisms.
- $K = QQ(root(4, 2))$: we have that $QQ(root(4, 2))=QQ(sqrt(2))(root(4, 2))$ then $[QQ(root(4, 2)):QQ]=[QQ(root(4, 2)), QQ(sqrt(2))][QQ(sqrt(2)):QQ] = 2 dot 2 = 4$ and $X^4 - 2$ nullifies $root(4, 2)$ then we have that $Irr(root(4, 2), QQ, X)=X^4-2$, and we get that the set of conjugates of $root(4, 2)$ over $QQ$ are ${root(4, 2), -root(4, 2), i root(4, 2), -i root(4, 2)}$ and since $char(QQ)=0$ then the following 4 embeddings are the only ones

#align(center)[
  #table(
    columns: 2,
    align: (left, left),
    gutter: 0.2cm,
    stroke: 0mm,
    [$sigma_1: root(4, 2) |-> root(4, 2)$],
    [$sigma_2: root(4, 2) |-> -root(4, 2)$],
    [$sigma_3: root(4, 2) |-> i root(4, 2)$],
    [$sigma_4: root(4, 2) |-> -i root(4, 2)$]
  )
]
and only $sigma_1, sigma_2$ are automorphisms.

- $K = QQ(root(3, 5))$: we have that $X^3 - 5$ is $5$-Eisenstein and nullifies $root(3, 5)$ then $Irr(root(3, 5), QQ, X)=X^3 - 5$ so the conjugates of $root(3, 5)$ over $QQ$ are ${root(3, 5), j root(3, 5), j^2 root(3, 5)}$ with $j = e^((2 pi) / 3 i)$, thus we get exactly $3$ embeddings
$
  sigma_1&: root(3, 5) |-> root(3, 5)\
  sigma_2&: root(3, 5) |-> j root(3, 5)\
  sigma_3&: root(3, 5) |-> j^2 root(3, 5)
$
and only $sigma_1$ is an automorphism.

#qst[Find all $QQ(sqrt(2))$-embeddings of $QQ(root(4, 2))$ into $CC$.]
we have that $[QQ(root(4, 2)):QQ(sqrt(2))]=2$ and its easy to verify that $Irr(root(4, 2), QQ(sqrt(2)), X)=X^2 - sqrt(2)$, thus the conjugates of $root(4, 2)$ over $QQ(sqrt(2))$ are ${root(4, 2), -root(4, 2)}$ thus we get only two embeddings since $char QQ(sqrt(2)) = 0$ which are
$
  sigma_1&: root(4, 2) |-> root(4, 2)\
  sigma_2&: root(4, 2) |-> -root(4, 2)
$

#qst[Determine all embeddigns of $K=FF_2(alpha)$ into an algebraic closure $overline(K)$ and all automorphisms with $alpha^2 + alpha + 1 = 0$ then $alpha^3 + alpha^2 + 1 = 0$.]
- $alpha^2 + alpha + 1 = 0$ : let $P(X) = X^2 + X + 1$, $P(0)=P(1)=1 != 0$ thus $P$ is irreducible over $FF_2[X]$ and $P(alpha)= 0$ so $Irr(alpha, KK, X) = P(X)$, $[FF_2(alpha):FF_2]=2$ thus there are two conjugates of $alpha$ over $FF_2$. $P(alpha^2) = alpha^4 + alpha^2 + 1$, we have $alpha^2 + alpha + 1 = 0 => alpha^2 = alpha + 1 => alpha^3 = 1 => alpha^4 = alpha$ thus $P(alpha^2) = alpha^2 + alpha + 1 = 0$. So the conjugates are ${alpha, alpha^2}$ and thus we get the embeddings are
$
  sigma_1&: alpha |-> alpha\
  sigma_2&: alpha |-> alpha^2
$
which are both automorphisms.

#qst[Determine all embeddigns of $K=FF_3(beta)$ into an algebraic closure $overline(K)$ and all automorphisms with $beta^2+beta+2=0$ then $beta^3+beta^2+2=0$.]
- the process is just the same as before.

#colbreak()
#exr[Let $L\/K$ be an algebraic extension and $Omega$ an algebraically closed field.]
#qst[Let $theta in L$, and $tau: K -> Omega$ an embedding, show that $tau$ can be extended to $sigma: K(theta) -> Omega$.]
#qst[If $char K = 0$ and $[K(theta):K]=n$ then there is exactly $n$ extensions to $K(theta)$.]
#qst[Apply the above to each embedding $sigma:QQ(sqrt(2))->CC$ with $theta=root(4, 2)$.]
#qst[Using the $1.3.1$ and Zorn's Lemma, prove that $tau$ can be extended to $sigma: L -> Omega$.]

#exr[Find the primitive element of the following extensions
  + $QQ(sqrt(2), i) \/ QQ$.
  + $CC\/RR$.
  + $QQ(sqrt(2), i, sqrt(3)) \/ QQ(sqrt(3))$.
  + $QQ(sqrt(2), i, sqrt(3)) \/ QQ$.
  + $QQ(sqrt(2), sqrt(3), root(4, 2)) \/ QQ$.
  + $FF_2(alpha, alpha^2, alpha + alpha^2) \/ FF_2$ with $alpha^2 + alpha + 1 = 0$.
]
+ $QQ(sqrt(2), i)\/QQ$, we consider two methods to find the primitive element
  + Let $theta = i + sqrt(2)$, we have that $theta - i = sqrt(2) => (theta - i)^2 = 2$, by distributing the factors, we have $theta^2 - 2 i theta + 1 = 2 => i = (theta^2 - 3)/(2 theta) in QQ(theta)$ and also $sqrt(2) = theta - i in QQ(theta)$ thus we get that $QQ(i, sqrt(2)) = QQ(theta)$.
  + By Eisenstein criterion we have $
    Irr(sqrt(2), QQ, X) &= X^2 - 2 \
    Irr(i, QQ, X) &= X^2 + 1
   $ thus the conjugates of $sqrt(2)$ are ${sqrt(2), -sqrt(2)}$ and of $i$ are ${i, -i}$, thus by the proof of the primitive element theorem, by taking $k in.not {0, i sqrt(2)}$ thus by taking $k=1$ we get $QQ(i, sqrt(2)) = QQ(i + sqrt(2))$.
+ $CC \/ RR$, its clear that $CC = RR(i)$ thus $i$ is a primitive element.
+ $QQ(sqrt(2), i, sqrt(3)) \/ QQ(sqrt(3))$, we have $QQ(sqrt(2), i, sqrt(3)) = QQ(sqrt(2), sqrt(i))(sqrt(3)) = QQ(sqrt(2) + sqrt(i))(sqrt(3)) = QQ(sqrt(3))(sqrt(2) + i)$ thus $sqrt(2) + i$ is a primitive element of $QQ(sqrt(2), i, sqrt(3)) \/ QQ(sqrt(3))$.
+ $QQ(sqrt(2), sqrt(3), i) \/ QQ$, we have from before that $QQ(sqrt(2), i)=QQ(sqrt(2) + i)$, thus $QQ(sqrt(2), sqrt(3), i) = QQ(sqrt(2) + i)(sqrt(3))$, now consider $theta = sqrt(2)+i$ we have then $
  (theta - i)^2 = 2 &=> theta^2 - 3 = 2 theta i\
  &=> (theta^2 - 3)^2 = -4 theta^2\
  &=> theta^4 - 2 theta^2 + 9 = 0
$ 
we can see that $theta$ is a root of $P(X) = X^4 - 2 theta^2 + 9$, notice that if $a$ is a root of $P$ then so is $-a$, $overline(a)$ and $-overline(a)$ thus we get that the conjugates of $theta$ are $sqrt(2) + i, -sqrt(2) + i, sqrt(2) - i, - sqrt(2) - i$ and we know that the conjugates of $sqrt(3)$ over $QQ$ are $sqrt(3)$ and $-sqrt(3)$, by the proof of the primitive element theorem we have that $k in.not {0, sqrt(2\/3), i\/sqrt(3), (sqrt(2) + i) \/ sqrt(3)$}, so taking $k=1$ we get that $sqrt(2) + sqrt(3) + i$ is a primitive element.

+ $QQ(root(4, 2), sqrt(2), sqrt(3))= QQ(sqrt(3), root(4, 2))$ with the same method.
+ $FF(alpha, alpha^2, alpha^2 + alpha) \/ FF$, its easy to notice that $alpha + alpha ^ 2 in FF(alpha, alpha^2)$ and from the definition of $alpha$, $alpha ^2 = alpha + 1 in FF(alpha)$ thus we get $
  FF(alpha, alpha^2, alpha^2 + alpha)
  = FF(alpha, alpha^2)
  = FF(alpha) (alpha^2) 
  = FF(alpha)
$ thus $alpha$ is a primitive element.

#exr[Let $K$ be a field with $char K = 0$, $L\/K$ an $n$-degree extension and $theta$ a primitive element of $L\/K$ and an algebraically closed field $Omega$.]
#qst[Showing that $1, theta, dots, theta^(n-1)$ is a basis of the vector space $L$ over $K$.]
#qst[Proving that the embeddings $sigma_i: L -> Omega$ are of the forma $sigma_i (theta)=theta_i$ where $theta_1, dots, theta_n$ are distinct conjugates of $theta$ over $K$.]
#qst[For any $eta in L$, the conjugates of $eta$ are contained in ${sigma_i (eta) | i in [|1,n|]}$.]
#qst[$eta$ is a primitive element if and only if $forall i, j in [|1, n|], sigma_i (eta) = sigma_j (eta) => i = j$.]
#qst[Deduce that for any $(a, b) in QQ^star times QQ^star$ we have $QQ(sqrt(2), sqrt(3)) = QQ(a sqrt(2) + b sqrt(2))$.]

#exr[Let $alpha = root(3, 2)$, $omega = e^((2 pi)/3 i)$ and $beta = alpha omega$, prove the following statements]
#qst[For any $c in QQ$, $gamma = alpha + c beta$ is a zero of $x^6 + a x^3 + b$ for some $a, b in QQ$.]
#qst[the polynomial $Irr(alpha + beta, QQ, X)$ is cubic and $deg Irr(alpha - beta, QQ, X) = 6$. ]
#qst[$forall c in QQ^star$, $QQ(alpha, omega) = QQ(omega + c alpha)$.]
#qst[$QQ(omega, sqrt(5))=QQ(omega sqrt(5)).$]
