#import "@THR/Sum:1.0.0": *
#show: template

#let subset = $subset.eq$
#let Id = math.op("Id")
#let Ker = math.op("Ker")
#let Im = math.op("Im")
#let Irr = math.op("Irr")
#let iso = $tilde.equiv$

#sect("Tutorial Series 1: Remainders", level: 1)
#exr[
  Consider the ring of polynomials $ZZ[X]$ with indeterminate $X$.
]
#qst[Show that $ZZ[X]\/(X) tilde.equiv ZZ$.]
Take the map $phi: ZZ[X] -> ZZ$ such that $phi(a_0 + a_1 X + dots + a_n X^n) = a_0$, $phi$ is a ring homomorphism with $Ker phi = (X)$ and $Im phi = ZZ$ then by the first isomorphism theorem $ZZ[X]\/(X) tilde.equiv ZZ$.

#qst[Show that $(2)+(x)$ is not generated by a singleton.]
Suppose there exists $P in ZZ[X]$ such that $(P) = (2) + (X)$, since $2 in (2) + (X)$ then $2 in (P)$ so $2 = P Q$ with $Q in ZZ[X]$ but that means that $deg(P) + deg(Q) = 0 => deg P = 0$ so $P = p in ZZ$, since $2 in (p)$ then $p | 2 => p = plus.minus 1$ or $p = plus.minus 2$ which are both impossible since $1 in ZZ[X] \\ ((2) + (X))$ and $2+X in (2) + (X) \\ (2)$.

#qst[Deduce that $ZZ[X]$ is not a PID.]
- From 1.1.1 we have that $ZZ[X]$ is a PID and $X$ is irreducible then $(X)$ is a maximal ideal so $ZZ[X]\/(X)$ is a field but $ZZ[X]\/(X) tilde.equiv ZZ$ which means that $ZZ$ is a field, contradiction.
- From 1.1.2 we have that $(2) + (x)$ is an ideal of $ZZ[X]$ but it is not a principle ideal.

#qst[Is $ZZ[X]$ a Euclidean domain ?]
$ZZ[X]$ is not a Euclidean domain since it is not a PID.

#exr[
 
]
