#import "@THR/Sum:1.0.0": *
#show: template.with(mainpage: false)

#let subset = $subset.eq$
#let Id = math.op("Id")
#let Ker = math.op("Ker")
#let Im = math.op("Im")
#let Irr = math.op("Irr")
#let iso = $tilde.equiv$
#let char = math.op("Char")
#let card = math.op("#")

#section("Embeddings", level: 1)
#exr[
  Consider the ring of polynomials $ZZ[X]$ with indeterminate $X$.
]
#qst[Show that $ZZ[X]\/(X) tilde.equiv ZZ$.]
Take the map $phi: ZZ[X] -> ZZ$ such that $phi(a_0 + a_1 X + dots + a_n X^n) = a_0$, $phi$ is a ring homomorphism with $Ker phi = (X)$ and $Im phi = ZZ$ then by the first isomorphism theorem $ZZ[X]\/(X) tilde.equiv ZZ$.

#qst[Show that $(2)+(x)$ is not generated by a singleton.]
Suppose there exists $P in ZZ[X]$ such that $(P) = (2) + (X)$, since $2 in (2) + (X)$ then $2 in (P)$ so $2 = P Q$ with $Q in ZZ[X]$ but that means that $deg(P) + deg(Q) = 0 => deg P = 0$ so $P = p in ZZ$, since $2 in (p)$ then $p | 2 => p = plus.minus 1$ or $p = plus.minus 2$ which are both impossible since $1 in ZZ[X] \\ ((2) + (X))$ and $2+X in (2) + (X) \\ (2)$.

#qst[Deduce that $ZZ[X]$ is not a PID.]
- From 1.1.1 we have that $ZZ[X]$ is a PID and $X$ is irreducible then $(X)$ is a maximal ideal so $ZZ[X]\/(X)$ is a field but $ZZ[X]\/(X) tilde.equiv ZZ$ which means that $ZZ$ is a field, contradiction.
- From 1.1.2 we have that $(2) + (x)$ is an ideal of $ZZ[X]$ but it is not a principle ideal.

#qst[Is $ZZ[X]$ a Euclidean domain?]
$ZZ[X]$ is not a Euclidean domain since it is not a PID.

#exr[
  Find embeddings and automorphisms in the following cases.
]

#qst[
  $K=QQ(sqrt(2)), QQ(root(4, 2)), QQ(root(3, 5))$ and $L=CC$.
]

- $K = QQ(sqrt(2))$: we have that $Irr(sqrt(2), K, X)=X^2-2$ since it is a monic $2$-Eisenstein that nullifies $sqrt(2)$ and we have that $char QQ = 0$ and $[QQ(sqrt(2)):QQ]=2$ so there are only two embeddings
$
  sigma_1&: sqrt(2) |-> sqrt(2)\
  sigma_2&: sqrt(2) |-> -sqrt(2)
$
which are both automorphisms.
- $K = QQ(root(4, 2))$: we have that $QQ(root(4, 2))=QQ(sqrt(2))(root(4, 2))$ then $[QQ(root(4, 2)):QQ]=[QQ(root(4, 2)), QQ(sqrt(2))][QQ(sqrt(2)):QQ] = 2 dot 2 = 4$ and $X^4 - 2$ nullifies $root(4, 2)$ then we have that $Irr(root(4, 2), QQ, X)=X^4-2$, and we get that the set of conjugates of $root(4, 2)$ over $QQ$ are ${root(4, 2), -root(4, 2), i root(4, 2), -i root(4, 2)}$ and since $char(QQ)=0$ then the following 4 embeddings are the only ones

#align(center)[
  #table(
    columns: 2,
    align: (left, left),
    gutter: 0.2cm,
    stroke: 0mm,
    [$sigma_1: root(4, 2) |-> root(4, 2)$],
    [$sigma_2: root(4, 2) |-> -root(4, 2)$],
    [$sigma_3: root(4, 2) |-> i root(4, 2)$],
    [$sigma_4: root(4, 2) |-> -i root(4, 2)$]
  )
]
and only $sigma_1, sigma_2$ are automorphisms.

- $K = QQ(root(3, 5))$: we have that $X^3 - 5$ is $5$-Eisenstein and nullifies $root(3, 5)$ then $Irr(root(3, 5), QQ, X)=X^3 - 5$ so the conjugates of $root(3, 5)$ over $QQ$ are ${root(3, 5), j root(3, 5), j^2 root(3, 5)}$ with $j = e^((2 pi) / 3 i)$, thus we get exactly $3$ embeddings
$
  sigma_1&: root(3, 5) |-> root(3, 5)\
  sigma_2&: root(3, 5) |-> j root(3, 5)\
  sigma_3&: root(3, 5) |-> j^2 root(3, 5)
$
and only $sigma_1$ is an automorphism.

#qst[Find all $QQ(sqrt(2))$-embeddings of $QQ(root(4, 2))$ into $CC$.]
we have that $[QQ(root(4, 2)):QQ(sqrt(2))]=2$ and its easy to verify that $Irr(root(4, 2), QQ(sqrt(2)), X)=X^2 - sqrt(2)$, thus the conjugates of $root(4, 2)$ over $QQ(sqrt(2))$ are ${root(4, 2), -root(4, 2)}$ thus we get only two embeddings since $char QQ(sqrt(2)) = 0$ which are
$
  sigma_1&: root(4, 2) |-> root(4, 2)\
  sigma_2&: root(4, 2) |-> -root(4, 2)
$

#qst[Determine all embeddigns of $K=FF_2(alpha)$ into an algebraic closure $overline(K)$ and all automorphisms with $alpha^2 + alpha + 1 = 0$ then $alpha^3 + alpha^2 + 1 = 0$.]
- $alpha^2 + alpha + 1 = 0$ : let $P(X) = X^2 + X + 1$, $P(0)=P(1)=1 != 0$ thus $P$ is irreducible over $FF_2[X]$ and $P(alpha)= 0$ so $Irr(alpha, KK, X) = P(X)$, $[FF_2(alpha):FF_2]=2$ thus there are two conjugates of $alpha$ over $FF_2$. $P(alpha^2) = alpha^4 + alpha^2 + 1$, we have $alpha^2 + alpha + 1 = 0 => alpha^2 = alpha + 1 => alpha^3 = 1 => alpha^4 = alpha$ thus $P(alpha^2) = alpha^2 + alpha + 1 = 0$. So the conjugates are ${alpha, alpha^2}$ and thus we get the embeddings are
$
  sigma_1&: alpha |-> alpha\
  sigma_2&: alpha |-> alpha^2
$
which are both automorphisms.

#qst[Determine all embeddigns of $K=FF_3(beta)$ into an algebraic closure $overline(K)$ and all automorphisms with $beta^2+beta+2=0$ then $beta^3+beta^2+2=0$.]
- the process is just the same as before.

#colbreak()
#exr[Let $L\/K$ be an algebraic extension and $Omega$ an algebraically closed field.]
#qst[Let $theta in L$, and $tau: K -> Omega$ an embedding, show that $tau$ can be extended to $sigma: K(theta) -> Omega$.]

#ooc[
   Define the map $
    dot.c^(tau): K[X] &-> K^tau [X] = tau(K)[X] \
  P(X) = sum_(i=0)^n a_i X^i &|-> P^tau (X) = sum_(i=0)^n tau(a_i) X^i
  $
  - $dot.c^tau$ is an isomorphism:
    - $dot.c^tau$ is an homomorphism: Let $P(X) = sum_(i=0)^n p_i X^i$ and $Q(X) = sum_(i=0)^n q_i X^i$ we have $
      (P + Q)^tau (X) &= sum_(i=0)^(n) tau(p_i + q_i) X^i \
        &= sum_(i=0)^n (tau(p_i) + tau(q_i)) X^i\
        &= P^tau (X) + Q^tau (X)\
      (P Q)^tau &= sum_(i=0)^(2n) tau(sum_(j=0)^i p_j q_(i - j)) X^i\
        &= sum_(i=0)^(2n) sum_(j=0)^i tau(p_j) tau(q_(i-j)) X^i\
        &= P^tau Q^tau
    $
    - $dot.c^tau$ is bijective: its surjective by definition $
      Ker dot.c^tau &= {P in K[X] | P^tau (X) = 0}\
        &= {P in K[X] | sum_(i=0)^n tau(p_i) X^i = 0}\
        &= {P in K[X] | forall i in [|1, n|], tau(p_i) = 0}\
        &= {P in K[X] | p_i = 0} = {0}
    $
  #v(-1mm)

  - $dot.c^tau$ preserves irreduciblility, that is, if $P$ is irreducible in $K[X]$ then it is irreducible in $K^tau [X]$:
    - Suppose that $P$ is irreducible and $P^tau$ is reducible, so $P^tau (X) = Q(X) R(X)$ then $P(X) = (Q(X) R(X))^(tau^(-1)) = Q^(tau^(-1))(X) R^(tau^(-1)) (X)$ and thus $P$ is reducible, contradiction.

  #v(-1mm)
  - Consider $P(X) = Irr(theta, K, X)$, $P^tau (X)$ is irreducible, and $K^tau subset Omega$ and $Omega$ is algebraically closed thus there is an element $theta' in Omega$, $P^tau (theta') = 0$. We define the map $
    phi: K[X] &-> K^tau [X]\/(P^tau (X))\
    Q(X) &|-> Q^tau (X) + (P^tau (X))
  $
  - $phi$ is a homeomorphism which is easy to verify $
      Ker phi &= {Q in K[X] | phi(Q) = (P^tau (X)) }\
        &= {Q in K[X] | Q^tau (X) = P^tau (X) R(X)}\
        &= {Q in K[X] | Q(X) = P(X) R^(tau^(-1)) (X)}\
        &= (P(X))
    $
  By applying the First Isomorphism Theorem we get that $phi$ is an isomorphism between $K(theta) iso K[X]\/(P(X)) iso K^tau [X]\/(P^tau (X)) iso K^tau (theta')$
]

#qst[If $char K = 0$ and $[K(theta):K]=n$ then there is exactly $n$ extensions to $K(theta)$.]

#qst[Apply the above to each embedding $sigma:QQ(sqrt(2))->CC$ with $theta=root(4, 2)$.]
#qst[Using the $1.3.1$ and Zorn's Lemma, prove that $tau$ can be extended to $sigma: L -> Omega$.]

#exr[Find the primitive element of the following extensions
  + $QQ(sqrt(2), i) \/ QQ$.
  + $CC\/RR$.
  + $QQ(sqrt(2), i, sqrt(3)) \/ QQ(sqrt(3))$.
  + $QQ(sqrt(2), i, sqrt(3)) \/ QQ$.
  + $QQ(sqrt(2), sqrt(3), root(4, 2)) \/ QQ$.
  + $FF_2(alpha, alpha^2, alpha + alpha^2) \/ FF_2$ with $alpha^2 + alpha + 1 = 0$.
]
+ $QQ(sqrt(2), i)\/QQ$, we consider two methods to find the primitive element
  + Let $theta = i + sqrt(2)$, we have that $theta - i = sqrt(2) => (theta - i)^2 = 2$, by distributing the factors, we have $theta^2 - 2 i theta + 1 = 2 => i = (theta^2 - 3)/(2 theta) in QQ(theta)$ and also $sqrt(2) = theta - i in QQ(theta)$ thus we get that $QQ(i, sqrt(2)) = QQ(theta)$.
  + By Eisenstein criterion we have $
    Irr(sqrt(2), QQ, X) &= X^2 - 2 \
    Irr(i, QQ, X) &= X^2 + 1
   $ thus the conjugates of $sqrt(2)$ are ${sqrt(2), -sqrt(2)}$ and of $i$ are ${i, -i}$, thus by the proof of the primitive element theorem, by taking $k in.not {0, i sqrt(2)}$ thus by taking $k=1$ we get $QQ(i, sqrt(2)) = QQ(i + sqrt(2))$.
+ $CC \/ RR$, its clear that $CC = RR(i)$ thus $i$ is a primitive element.
+ $QQ(sqrt(2), i, sqrt(3)) \/ QQ(sqrt(3))$, we have $QQ(sqrt(2), i, sqrt(3)) = QQ(sqrt(2), sqrt(i))(sqrt(3)) = QQ(sqrt(2) + sqrt(i))(sqrt(3)) = QQ(sqrt(3))(sqrt(2) + i)$ thus $sqrt(2) + i$ is a primitive element of $QQ(sqrt(2), i, sqrt(3)) \/ QQ(sqrt(3))$.
+ $QQ(sqrt(2), sqrt(3), i) \/ QQ$, we have from before that $QQ(sqrt(2), i)=QQ(sqrt(2) + i)$, thus $QQ(sqrt(2), sqrt(3), i) = QQ(sqrt(2) + i)(sqrt(3))$, now consider $theta = sqrt(2)+i$ we have then $
  (theta - i)^2 = 2 &=> theta^2 - 3 = 2 theta i\
  &=> (theta^2 - 3)^2 = -4 theta^2\
  &=> theta^4 - 2 theta^2 + 9 = 0
$ 
we can see that $theta$ is a root of $P(X) = X^4 - 2 theta^2 + 9$, notice that if $a$ is a root of $P$ then so is $-a$, $overline(a)$ and $-overline(a)$ thus we get that the conjugates of $theta$ are $sqrt(2) + i, -sqrt(2) + i, sqrt(2) - i, - sqrt(2) - i$ and we know that the conjugates of $sqrt(3)$ over $QQ$ are $sqrt(3)$ and $-sqrt(3)$, by the proof of the primitive element theorem we have that $k in.not {0, sqrt(2\/3), i\/sqrt(3), (sqrt(2) + i) \/ sqrt(3)$}, so taking $k=1$ we get that $sqrt(2) + sqrt(3) + i$ is a primitive element.

+ $QQ(root(4, 2), sqrt(2), sqrt(3))= QQ(sqrt(3), root(4, 2))$ with the same method.
+ $FF(alpha, alpha^2, alpha^2 + alpha) \/ FF$, its easy to notice that $alpha + alpha ^ 2 in FF(alpha, alpha^2)$ and from the definition of $alpha$, $alpha ^2 = alpha + 1 in FF(alpha)$ thus we get $
  FF(alpha, alpha^2, alpha^2 + alpha)
  = FF(alpha, alpha^2)
  = FF(alpha) (alpha^2) 
  = FF(alpha)
$ thus $alpha$ is a primitive element.

#exr[Let $K$ be a field with $char K = 0$, $L\/K$ an $n$-degree extension and $theta$ a primitive element of $L\/K$ and an algebraically closed field $Omega$.]
#qst[Showing that $1, theta, dots, theta^(n-1)$ is a basis of the vector space $L$ over $K$.]
#qst[Proving that the embeddings $sigma_i: L -> Omega$ are of the forma $sigma_i (theta)=theta_i$ where $theta_1, dots, theta_n$ are distinct conjugates of $theta$ over $K$.]
#qst[For any $eta in L$, the conjugates of $eta$ are contained in ${sigma_i (eta) | i in [|1,n|]}$.]
#qst[$eta$ is a primitive element if and only if $forall i, j in [|1, n|], sigma_i (eta) = sigma_j (eta) => i = j$.]
#qst[Deduce that for any $(a, b) in QQ^star times QQ^star$ we have $QQ(sqrt(2), sqrt(3)) = QQ(a sqrt(2) + b sqrt(3))$.]

#exr[Let $alpha = root(3, 2)$, $omega = e^((2 pi)/3 i)$ and $beta = alpha omega$, prove the following statements]
#qst[For any $c in QQ$, $gamma = alpha + c beta$ is a zero of $x^6 + a x^3 + b$ for some $a, b in QQ$.]
#qst[the polynomial $Irr(alpha + beta, QQ, X)$ is cubic and $deg Irr(alpha - beta, QQ, X) = 6$. ]
#qst[$forall c in QQ^star$, $QQ(alpha, omega) = QQ(omega + c alpha)$.]
#qst[$QQ(omega, sqrt(5))=QQ(omega sqrt(5)).$]

#pagebreak()
#__cbox-count.update(0)
#section("Finite Fields", level: 1)
#exr[
  Decide whether there exists a finite field having the given number of elements.
  $ 4095 #h(2mm) - #h(2mm) 191 #h(2mm) - #h(2mm) 12345678910\ 81 #h(2mm) - #h(2mm) 12396 #h(2mm) - #h(2mm) 128 $
]

the fields have a cardinal of the form $p^n$ with $p$ prime, If a number has more than one prime divisor then it is not of the form $p^n$ thus there is no field with such cardinality. There are no fields with cardinality $4095, 12345678910, 12396$ since their prime decomposition have multiple primes while $191, 81, 128$ are powers of primes thus there exists a field having their cardinality which are $FF_(191), FF_(3^4), FF_(2^7)$ respectively.

#exr[
  Determine all finite fields having $n$ elements where $n <= 15$. Find a basis, a primitive element, a generator for the multiplicative group for every field.
]

We will find all the fields of the form $FF_(p^n)$ such that $p^n <= 15$.
- $p = 2$:
  - $n = 1$:
    - Field: $FF_2$.
    - Primitive Element: $1$ or $0$.
    - Basis Over $FF_2$: ${1}$.
    - Generator: $1$.
  - $n = 2$:
    - Field: $FF_(2^2) = FF_4$.
    - Primitive Element: $alpha$ with $alpha^2 + alpha + 1 = 0$.
    - Basis Over $FF_2$: ${1, alpha}$
    - Generator: $alpha$.
  - $n = 3$:
    - Field: $FF_(2^3) = FF_8$.
    - Primitive Element: $alpha$ with $alpha^3 + alpha + 1 = 0$.
    - Basis Over $FF_2$: ${1, alpha, alpha^2}$.
    - Generator: $alpha$.

- $p = 3$:
  - $n = 1$:
    - Field: $FF_3$.
    - Primitive Element: $1$ or $0$.
    - Basis Over $FF_3$: ${1}$.
    - Generator: $2$.
  - $n = 2$:
    - Field: $FF_(3^2) = FF_9$.
    - Primitive Element: $alpha$ with $alpha^2 + 1 = 0$.
    - Basis Over $FF_3$: ${1, alpha}$.
    - Generator: $$.

- for the remaining for any $p in {5, 7, 11, 13}$ we have
  - Field: $FF_p$.
  - Primitive Element: $1$ or $0$.
  - Basis Over $FF_p$: ${1}$.
  - Generator:  respectively.

#exr[
  Let $p$ denote a prime number and let $m, n$ be positive integers.
]

#qst[
  Let $P in FF_p [X]$ be irreducible, show that $P$ is a factor of the polynomial $X^(p^n) - X$ for some $p$ prime and $n in NN$.
]

#qst[
  Prove that a finite field with $p^n$ eleemnts admits exactly one subfield having $p^m$ elements for each divisors of $m$ in $n$.
]

#qst[
  Suppose $FF_(p^m)$ is a subfield of $FF_(p^n)$ prove that $m$ divides $n$.
]

#qst[
  Deduce that the number of subfields of $FF_(p^n)$ is equal to the number of divisors of $n$.
]

#exr[
  Let $p$ be a prime number and $n in NN$, show that the polynomial $x^(p^n) - x in FF_p [X]$ is the product of all irreducible monic polynomials in $FF_p [X]$ with degrees dividing $n$.
]

#exr[Verify certain results from Chapter 2]

#qst[
  Using thhe fact that $P_0(X) = X^2 + X + 1$ is the unique quadratic irreducible element of $FF_2 [X]$. Prove that the polynomials $P_1 (X) = X^4 + X + 1, P_2 (X) = X^4 + X^3 + 1, P_3 (X) = X^4 + X^3 + X^2 + X + 1$ are irreducible over $FF_2$.
]

#qst[
  Let $alpha, beta, gamma$ be the zeros of $P_1, P_2, P_3$ respectively, in a fixed algebraic closure $overline(FF_2)$. Find bases of $FF_2 (alpha), FF_2 (beta), FF_2 (gamma)$, what is the number of elements of each of these fields.
]

#qst[
  Show that $1\/beta$ is a conjugate of $alpha$ and $1 + gamma$ is a conjugate of $beta$ over $FF_2$.
]

#qst[
  Express $alpha^5$ in terms of $1, alpha, alpha^2, alpha^3$. Deduce that $alpha$ generates $FF_2 (alpha)^*$.
]

#qst[
  Express $alpha^8$ in terms of $1, alpha, alpha^2, alpha^3$. Deduce that the conjugates of $alpha$ over $FF_2$ are $alpha, alpha^2, alpha^4, alpha^8$.
]

#qst[
  Deduce from the the last two points that $beta$ generates $FF_2 (beta)^*$ and the set of conjugates of $beta$ over $FF_2$ is ${alpha^(14), alpha^(13), alpha^(11), alpha^7}$.
]

#qst[
  Verify that the set of conjugates of $gamma$ over $FF_2$ is ${alpha^3, alpha^6, alpha^9, alpha^12}={gamma, gamma^2, gamma^4, gamma^8}$, $FF_2 (alpha) = FF_2 (beta) = FF_2 (gamma)$ and the order of $gamma$ in the group $FF_2 (gamma)^*$ is $5$.
]

#qst[
  Prove that $alpha^5$ and $alpha^10$ are zeros of $P_0$ and $FF_2 (alpha^5)$ is a quadratic subfield of $FF_2 (alpha)$. Verify that the decomposition of the polynomial $X^16 - X$ into irreducible elements of $FF_2 [X]$ is given by $X(X-1)P_0P_1P_2P_3$.
]

#pagebreak()
#__cbox-count.update(0)
#section("Normal Extensions", level: 1)

#exr[
  Decide whether each of the following extensions is normal:
  + $QQ(sqrt(2), i) \/ QQ$.
  + $CC\/R$.
  + $QQ(sqrt(2), sqrt(3), i) \/ QQ$.
  + $QQ(sqrt(2), root(4, 2)) \/ QQ$.
  + $QQ(sqrt(2), sqrt(3), root(4, 2)) \/ QQ(root(4, 2))$.
  + $QQ(root(3, 5), i) \/ QQ$.
  + $QQ(sqrt(2), sqrt(3), root(4, 2)) \/ QQ(sqrt(2))$
  + $FF_2 (alpha, beta, alpha + beta) \/ FF_2$ with $alpha^2 + alpha + 1 = 0$ and $beta^(2025) + beta + 1 = 0$.
]

#exr[
  Show in three different ways that each of the following field extensions $L\/K$ is normal.
]

#qst[$L = K$.]
+ *Conjugates:* Let $alpha in K$ then $Irr(alpha, K, X) = X-alpha$ which has exactly one root $alpha$ which is in $K$, so all conjugates of $alpha$ are in $L$, thus $L\/K$ is normal.
+ *Splitting Field:* Take the family $cal(F) = { X - alpha | alpha in K }$ so every $f in cal(F)$ splits over $K$ since $forall alpha in K, K(alpha) = K$. So $L\/K$ is normal since it's splitting field of the family $cal(F)$.
+ *Embeddings:* Let $sigma: L -> overline(K)$ be a $K$-embedding into $overline(K)$. since $sigma$ is the identity on $K$ then its an automorphism so $L\/K$ is normal.

#qst[$L$ is an algebraic closure of $K$.]
+ *Definition:* Let $P in K[X]$ irreducible and $alpha in L$ such that $P(alpha) = 0$. As $L$ is the algebraic closure then $L$ is algebraically closed thus all zeros of $P$ are in $L$ and we have that $L\/K$ is normal.
+ *Splitting Field:* Since $L$ is the algebraic closure of $K$ then $L$ is the splitting field of the family $cal(F) = K[X]$ thus the extension $L\/K$ is normal.
+ *Embeddings:* Let $sigma: L -> overline(K) = L$ is an endomorphism and since it is an $K$-embedding and $L\/K$ is algebraic then $sigma$ is surjective by the course Proposition 1.1.6 thus it is an automorphism from $L$ to $L$.

#qst[$L$ is a quadratic extension of $K$.]
#nte[
  If $[L:K] = p$ prime number, then there exists $theta$ a primitive element for $L\/K$, that is because by taking $theta in L$, $K subset K(theta) subset L$ and we have that $[L:K] = [L:K(theta)] dot.c [K(theta):K]$ and thus we get that $[K(theta):K] = 1$ if and only if $theta in K$ thus by taking $theta in L \\ K$ we have that $[K(theta):K] = p$ necessarily and thus $K(theta) = L$.
]
+ *Conjugates:* Let $theta in L$, if $[K(theta):K]=1$ then the conjugates of $theta$ is just $theta$ which is in $K(theta)$, else if $[K(theta):K] = 2$ then $Irr(theta, K, X) = X^2 + a X + b$, let $theta'$ be the conjugate of $theta$ over $K$, then $Irr(theta, K, X) = (X - theta) (X - theta') = X^2 - (theta + theta') X + theta theta' in K[X]$ thus $a = theta + theta' in K$ and we get $theta' = a - theta in K(theta) subset L$ thus the conjugates of $theta$ which are $theta, theta'$ are in $L$ thus it is normal.

#exr[
  Show that the degree of a splitting field of the polynomial $X^p - 1 in QQ[X]$ over $QQ$ with $p$ prime is equal to $p-1$.
]
Consider $P(X) = X^p - 1 = (X-1)(X^(p-1) + dots.c + X + 1) = (X-1)Phi(X)$, $Phi(X)$ is irreducible and its zeros are the roots of unity thus the splitting field of $P$ is $QQ(xi)$, $xi = e^((2 pi)/p i)$ which has degree $[QQ(xi), QQ] = deg Phi = p - 1$. The polynomial $phi(X)$ is irreducible since $phi(X + 1)$ is $p$-Eisenstein.
#qst[Give another proof for Proposition 3.10]
Let $sigma$ be a $L$-embedding of $L$ into $Omega$, since $K subset L$ then $sigma$ is a $K$-embedding of $L$ into $Omega$ since $M\/K$ is normal then $sigma$ is an isomorphism of $M$.

#exr[]

#qst[
  Find the normal closure of the following fields.
  + $QQ(sqrt(2)) \/ QQ$.
  + $QQ(root(3, 5)) \/ QQ$.
  + $CC \/ QQ(sqrt(3))$.
  + $QQ(sqrt(2), root(3, 3), root(5, 5)) \/ QQ$.
  + $QQ(root(40, 2)) \/ QQ(root(20, 2))$.
  + $QQ(sqrt(2), sqrt(3), root(4, 2)) \/ QQ(root(4, 2))$.
  + $QQ(root(3, 5), i) \/ QQ$.
]

#ooc[
  + $QQ(sqrt(2)) \/ QQ$ is normal thus the algebraic closure.
  + $QQ(root(3, 5)) \/ QQ$, $root(3, 5)$ is a root of $X^3 - 5$ which is $5$-Eisenstein and thus $Irr(root(3, 5), QQ, X) = X^3 - 5$, and thus the extension $QQ(root(3, 5), j root(3, 5), j^2 root(3, 5)^2)=QQ(root(3, 5), j root(3, 5))$ is the normal closure of $QQ(root(3, 5))$ which is normal since it is the splitting field of $X^3 - 5$.
  + $CC\/QQ(sqrt(3))$ is a normal extension since $CC$ is an algebraically closed field containing $QQ$ then $CC\/QQ$ is normal and since $QQ subset QQ(sqrt(3)) subset CC$ then $CC\/QQ(sqrt(3))$ is normal.
  + $QQ(sqrt(2), root(3, 3), root(5, 5)) \/ QQ$: we have that $Irr(sqrt(2), QQ, X) = X^2 - 2, Irr(root(3, 3), QQ, X) = X^3 - 3, Irr(root(5, 5), QQ, X) = X^5 - 5$ and thus by considering the family $cal(F) = {X^2 - 2, X^3 - 3, X^5 - 5}$ we get that the normal closure of $QQ(sqrt(2), root(3, 3), root(5, 5))$ is $QQ(sqrt(2), root(3, 3), root(5, 5), j, xi)$ where $xi$ is a root of $X^5 - 1 = 0$.
  + $QQ(root(40, 2))\/QQ(root(20, 2))$
]

#qst[Let $alpha, beta in overline(K)$, and $S_alpha, S_beta$ the splitting fields of $Irr(alpha, K, X)$ and $Irr(beta, K, X)$.]


#pagebreak()

#ooc[
  #section(level: 1, [Series: Groups.])

  #exr[
    Let $G$ be a group such that the intersection of all its subgroups other than ${e}$ is a subgroup of $G$ different from ${e}$. Prove that every element of $G$ has a finite order.
  ]
  Let ${H_i}_(i in I)$ be the set of non-trivial subgroups of $G$, and suppose $exists y in inter.big_(i in I) H_i \\ {e}$. Let $x in G$, we have that $chevron.l x chevron.r$ is a subgroup of $G$ thus $y in chevron.l x chevron.r$ and since it is a subgroup then $y^(-1) in chevron.l x chevron.r$ too, thus $exists n, m in ZZ\\{0}$ (this comes from the fact that $y != e$), $y = x^n, y^(-1) = x^m$ and thus we have that $x^(n+m) = x^n dot.c x^m = y dot.c y^(-1) = e$ hence $x$ has finite order.

  #exr[
    Let $G$ be a group, $H$ a subgroup of $G$ and $a in G$, prove that $a H a^(-1)$ is a subgroup of $G$ isomorphic to $H$. What happens when $H$ is finite, $H$ is normal.
  ]
  + *$a H a^(-1)$ is a subgroup of $G$*:
    - $e = a a^(-1) = a e a^(-1) in a H a^(-1)$.
    - Let $a x a^(-1), a y a^(-1) in a H a^(-1)$, $(a x a^(-1))^(-1) a y a^(-1) = a x^(-1) a^(-1) a y a^(-1) = a (x^(-1) y) a^(-1) in a H a^(-1)$.
  + *$a H a^(-1)$ is isomorphic to $H$*:\
    Consider the map $phi: H -> a H a^(-1), x |-> a x a^(-1)$, we have $Im phi = a H a^(-1)$ by definition, and $Ker phi = {h in H | a h a^(-1) = e} = {h in H | h = a^(-1) a = e} = {e}$ thus $phi$ is an isomorphism from $H$ to $a H a^(-1)$.
  + *What happens when*
    - $H$ is normal in $G$: then $a H a^(-1) = H$ for any $a in G$.
    - $H$ is finite: ?

  #exr[
    Let $H$ and $K$ be two subgroups of $G$ with finite indices in $G$. Prove that $H inter K$ is of finite index in $G$, and find an upperbound for this index.
  ]
  Suppose $[G:H]$ and $[G:K]$ are finite. We have $
    [G: H inter K] &= card G\/(H inter K)\
    &= card {g (H inter K) | g in G}\
    &= card {(g H) inter (g K) | g in G}\
    &<= card {(g H) inter (g' K) | g, g' in G}\
    &<= card {h inter k | h in G\/H, k in G\/K}\
    &<= card G\/H dot.c card G\/K = [G:H] dot.c [G:K].
  $ the last inequality comes from the fact that if $h inter k = h' inter k'$ then $exists x in (h inter k) inter (h' inter k') => x in (h inter h')$ and $x in (k inter k')$ so $h = h'$ and $k = k'$. Since both $[G:H]$ and $[G:K]$ are finite then so is $[G: H inter K] <= [G:H] dot.c [G:K]$.

  #exr[]
  #qst[
    Let $a$ be an element of $G$ and define $N(a) = {g in G | g a = a g}$. Show that $N(a)$ is a subgroup of $G$ called the normalized of $a$ in $G$.
  ]
  Let $x, y in N(a)$ we have that $a x = x a$ and $a y = y a$
    - $e in N(a)$: $e a = a = a e$.
    - $x^(-1) in N(a)$: $(a x)^(-1) = (x a)^(-1) => x^(-1) a^(-1) = a^(-1) x^(-1) => a x^(-1) = x^(-1) a$
    - $x y in N(a)$: $a (x y) = (a x) y = (x a) y = x (a y) = x (y a) = (x y) a$.
  Thus, $N(a)$ is a subgroup.

  #qst[
    Let $H$ be a subgroup of $G$, define
    - Centralizer: $Z(H) = {g in G | forall h in H, g h = h g}$.
    - Normalizer: $N(H) = {g in G | g H g^(-1) = H}$.
    Prove that $Z(H)$ and $N(H)$ are subgroups of $G$.
  ]
  - Centralizer: Notice that $Z(H) = inter.big_(h in H) N(h)$ which are all subgroups so $Z(H)$ is a subgroup.
  - Normalizer: let $x, y in N(H)$
    - $e in N(H)$: $e H e^(-1) = H$.
    - $x^(-1) in N(H)$: $x H x^(-1) = H => H = x^(-1) H x$.
    - $x y in N(H)$: $x y H (x y)^(-1) = x (y H y^(-1)) x^(-1) = x H x^(-1) = H$.

  #qst[
    - Prove that $H subset N(H)$.
    - Give an example of $Z(H) != N(H)$.
  ]
  - let $x in H$ then $forall h in H, x h x^(-1) in H$ since it is closed.
  - it is easy to notice that $Z(H) subset N(H)$. Consider $G = S_3$ and $H=chevron.l sigma chevron.r$ with $
    sigma = mat(0, 1, 2; 2, 0, 1)
  $ notice that $Z(H) = H$ and $N(H) = G$ so $Z(H) != N(H)$.

  #exr(count: false, ovcount: false)[
    - - Prove that $N(H)$ is the largest subgroup of $G$ in which $H$ is normal.
      - Prove that $H$ is normal in $G$ $<=>$ $N(H) = G$.
    - - Prove that $Z(G)$ is a normal subgroup in $G$.
      - Deduce that a group of order $9$ is abelian.
  ]

  - - It is clear that $H$ is normal in $N(H)$. Let $K$ be a subgroup of $G$ such that $H$ is normal in $K$, let $k in K$, since $H$ is normal in $K$ then $k H k^(-1) = H$ but since $K subset G$ then $k in N(H)$. Thus, $K subset N(H)$, $N(H)$ is the largest subgroup of $G$ where $H$ is normal.
    - $=>$ suppose $H$ is normal, then $forall g in G, g H g^(-1) = H$ thus $G subset N(H) subset G => G = N(H)$. $arrow.double.l$ if $N(H) = G$ then $forall g in G, g H g^(-1) = H$ so $H$ is normal in $G$.

  - - Proving that $Z(G)$ is a normal subgroup of $G$, let $z in Z(G), g in G$, $g z g^(-1) = (g z) g^(-1) = (z g) g^(-1) = z (g g^(-1)) = z in Z(G)$.
    - ?

  #exr[]
  #qst[
    Let $G$ be a finite group of order $p^2$. Show that $G$ is abelian when its center is not reduced to the identity element.
  ]
  Suppose $Z(G) != {e}$, then we have that $card G \/ Z(G) = p$ so $G \/ Z(G) iso F_p$ which is cyclic, and thus $G$ is abelian.

  #qst[
    Show that a group $G$ of order $6$ is isomorphic to $S_3$ or $ZZ_6$.
  ]
  - Case 1: $exists x in G, o(x) = 6$, then $G = chevron.l x chevron.r$ so $G iso ZZ_6$.
  - Case 2: $G$ has no element of order $6$.

  #exr[
    Let $G$ be a group and let $G' = {[x:y] | x, y in G}$ be the commutator of $G$.
  ]

  #qst[
    Prove that $G'$ is a normal subgroup of $G$.
  ]
  Let $g in G$, then let $x, y, g in G$, we have that $
    [g:[x:y]] &= g [x:y] g^(-1) [x:y]^(-1) \
    => g[x:y]g^(-1) &= [g:[x:y]][x:y]
  $ notice that both $[g:[x:y]],[x:y] in G'$ then $g [x:y] g^(-1) in G'$ so $forall g in G, g G' g subset G'$ so $G'$ is a normal subgroup of $G$.

  #qst[
    Prove that $G\/G'$ is abelian.
  ]
  Let $x, y in G$, $x G' dot.c y G' = x y G'$ but since $x, y in G$ then $[x:y] in G'$ so $[x:y]^(-1) in G'$, then $y x = [x:y]^(-1) x y in x y G'$ thus $x y G' = y x G'$ so the group $G\/G'$ is abelian.

  #qst[
    Let $H$ be a normal subgroup of $G$, if $G\/H$ is abelian then $G' subset H$.
  ]
  Let $H$ be a normal subgroup of $G$ and $G\/H$ is abelian. Let $x, y in G$ we have then $
    [x:y] H &= x y x^(-1) y^(-1) H\
    &= (x y) H dot.c (x^(-1) H) (y^(-1) H)\
    &= (x y) H dot.c (y^(-1) H) (x^(-1) H)\
    &= x y y^(-1) x^(-1) H = H
  $ thus $G' subset H$.

  #qst[
    If $H$ is a subgroup of $G$ and $G' subset H$, then $H$ is normal in $G$.
  ]
  Let $H$ be a subgroup of $G$ with $G' subset H$, let $g in G$ and $h in H$. We have that $[g:h] = g h g^(-1) h^(-1)$ thus $g h g^(-1) = [g:h] h^(-1)$, and since $[g:h] in G' subset H$ and $h^(-1) in H$ then $g h g^(-1) = [g:h] h^(-1) in H$ thus $H$ is normal in $G$.

  #exr[
    Let $n in NN$ and $s, r$ two formal variables satisfying $s^2 = e, r^n = e, s r = r^(-1) s$, define $D_(2 n) = {s^i r^i | i, j in NN}$.
  ]

  #qst[
    Find the number of subgroups of order $2$, $3$ of $D_(2 n)$.
  ]
  - Subgroups of order $2$: The subgroups of order $2$ should be of the form ${e, x}$ with $o(x) = 2$, thus we start with finding the elements of order $2$.
    - Case 1: $x=s r^k => x^2 = (s r^k)^2 = s r^k s r^(k) = s r^(k) r^(-k) s = s^2 = e$ thus any element of the form $s r^k$ is of order $2$.
    - Case 2: $x=r^k => x^2 = (r^k)^2 = r^(2k)$ but $r$ has order $n$ thus if $x$ is of order $2$, $n$ is even and we have that $x=r^(n\/2)$ is the only element of the form $r^k$ that has order $2$.
    To count now we have that the number of subgroups of order $2$, we count how many different elements of order $2$ do we have: we have $n$ elements from the first case $s r^k, k in [|0, n-1|]$, if $n$ is even then there is an extra element so:
      - if $n$ is even: $n + 1$ subgroups of order $2$.
      - if $n$ is odd: $n$ subgroups of order $2$.
  - Subgroups of order $3$: it is the same here, since any group of order $3$ is cyclic then necessarily any subgroup would be of the form $chevron.l x chevron.r$ where $o(x) = 3$.
    - Case 1: $x = s r^k => x^3 = (s r^k)^2 s r^k = s r^k = x$ thus $x = e$ so there is no element of the form $s r^k$ that has order $3$.
    - Case 2: $x = r^k => x^3 = r^(3k)$ then $3$ should divide $n$ and we get one element of order $3$.
    so same as before:
      - if $n$ is divisible by $3$: there is one subgroup of order $3$.
      - if $n$ is not divisible by $3$: there is no subgroup of order $3$.

  #qst[
    Determine the center of the Dihedral group $D_(2n)$.
  ]
  For the ease of calculation, we can easily prove by induction that $r^j s^i = s^i r^((-1)^i j)$, consider the element $x in cal(Z)(D_(2n))$ and $y in D_(2n)$ of the form $y = s^i r^j$ for all $i, j$, there are two cases
  - $x = r^k$: $x y = y x => r^k s^i r^j = s^i r^j r^k => s^i r^((-1)^i k) r^j = s^i r^j r^k => r^((-1)^i k) = r^(k) => r^((1 - (-1)^i) k) = e$ thus by taking $i$ odd we get that $2k = n$ so if $n$ is even then $r^(n\/2)$ is in the center.
  - $x = s r^k$: $x y = y x => s r^k s^i r^j = s^i r^j s r^k => s^(i+1) r^(j - k) = s^(i+1) r^(k - j) => (r^(j - k))^2 = e$ which is impossible for all $j$.
  Thus the center of $D_(2n)$ is $
    cal(Z)(D_(2n)) = cases(
      {e} "if" n "odd",
      {e, r^(n\/2)} "if" n "even"
    )
  $

  #colbreak()
  #qst[
    Prove that the commutator of $D_(2n)$ is generated by $r^2$.
  ]

  Let $x, y in D_(2n)$, $x = s^i r^j$ and $y = s^(i') r^(j')$ then $
    x y &= s^i r^j s^(i') r^(j')\
    &= s^i s^(i') r^((-1)^(i') j) r^(j')\
    &= s^(i + i') r^((-1)^(i') j + j')\
    x y x^(-1) &= s^(i+i') r^((-1)^(i') j + j') r^(-j) s^(-i)\
    &= s^(i + i') r^((-1)^(i') j + j' - j) s^(-i)\
    &= s^(i') r^((-1)^i ((-1)^(i') j + j' - j))\
    [x,y] = x y x^(-1) y^(-1) &= s^(i') r^((-1)^i ((-1)^(i') j + j' - j)) r^(-j') s^(-i') \
    &= s^(i') r^((-1)^i ((-1)^(i') j + j' - j) -j') s^(-i') \
    &= r^((-1)^(-i') ((-1)^i ((-1)^(i') j + j' - j) -j'))
  $ by expanding the last term we get $[x,y] = r^(((-1)^(i') - (-1)^i)j)$ and since $(-1)^i' - (-1)^i in {0, 2, -2}$ then $[x,y] in chevron.l r^2 chevron.r$, and by taking $k in NN, r^(2k) = [s r^k,r^k]$ thus $[D_(2n),D_(2n)] = chevron.l r^2 chevron.r$.

  #exr[
    Let $H$ and $K$ be two subgroups of $G$.
  ]

  #qst[
    Prove that if $H$ or $K$ is normal then $H K$ is a subgroup of $G$.
  ]
  Suppose that $H$ is normal, we have from the course that $H K$ is a subgroup if and only if $H K = K H$. Since $H$ is normal, then $forall k in K, k H k^(-1) = H$ and thus $forall k in K, k H = H k => K H = H K$, so $H K$ is a subgroup of $G$.

  #qst[
    Prove that if $H$ and $K$ are normal then so are $H K$ and $H inter K$.
  ]
  Suppose that $H$ and $K$ are normal
  - $H K$ is normal: Let $g in G$, $g H K g^(-1) = g H g^(-1) g K g^(-1) = (g H g^(-1)) (g K g^(-1)) = H K$ thus $H K$ is normal.
  - $H inter K$ is normal: Let $g in G$, $g (H inter K) g^(-1) = (g H g^(-1)) inter (g K g^(-1)) = H inter K$ thus $H inter K$ is normal.

  #qst[
    Prove that $H K \/ K$ and $H \/ (H inter K)$ are isomorphic.
  ]
  Define the map $phi: H -> H K, h |-> h$, it is well defined and it is a homomorphism. We have that $phi^(-1)(K) = {h in H | h in K} = H inter K$ and since $H inter K$ is normal in $G$ then it is in $H$ and thus we get by the course lemma that $ H\/(H inter K) iso H K\/K$.

  #qst[
    Prove that $H K \/ H$ and $K \/ (H inter K)$ are isomorphic.
  ]
  In similar fashion, take $phi: K -> H K, k |-> k$, $phi^(-1)(k) = K inter H$ and thus $H K \/ H iso K \/ (H inter K)$.

  #exr[
    Let $G$ be a non-abelian group of order $8$.
  ]

  #qst[
    Show there exists $y in G$ of order $4$ and $x in G\\H$ where $H = chevron.l y chevron.r$ and $G = H union x H$.
  ]
  Since the group is non-abelian then all non-neutral elements have order either $2$ or $4$. If every non-neutral element of $G$ has order $2$, then $G$ would be abelian since $forall x, y in G, x = x^(-1), y = y^(-1), x y = (x y)^(-1)$, $y x = y^(-1) x^(-1) = (x y)^(-1) = x y$, thus there is necessarily an element of order $4$, denote it $y$. Let $x in G\\H$, we have that $H inter x H = emptyset$ since if $H inter x H != emptyset$ then $exists n, m in NN, y^n = x y^m => x = y^(n-m) in H$ thus $x in H$ which is a contradiction, and since $H union x H subset G$ and $card (H union x H) = card H + card x H - card (H inter x H) = card H + card x H = 8$ then $H union x H = G$. ($card x H = 4$ since $forall n, m in NN, x y^n = x y^m => n = m mod 4$ thus are the same element).

  #qst[
    Prove that $x^2 in {e, y^2}$.
  ]
  We have that $G = H union x H$, since $G$ is a group then $x^2 in G => x^2 in H union x H$, $x^2 in.not x H$ since if it was, then $x^2 = x y^m => x = y^m in H$ which is a contradiction, thus $x^2 in H$. The order of $x$ is either $2, 4$ since the order of the element should divide the order of the group, if $x$ has order $2$ then $x^2 = e$, else then the order of $x^2$ is $2$, and the order of elements of $H$ are as follows: $o(y) = 4, o(y^2) = 2, o(y^3) = 4$ thus $x^2 = y^2$.

  #qst[
    Show that if $x y = y x$ then $forall i, j in ZZ, x^i y^j = y^j x^i$ thus $G$ is abelian.
  ]
  Suppose that $x y = y x$. We prove by double induction that $x^i y^j = y^j x^i$, it is enough to prove for $i, j in NN$ since $x, y$ have finite order.
  - $i = 0, j = 0$: $x^0 y^0 = e = y^0 x^0$.
  - suppose its true for $i, j$: 
    - $x^(i+1) y^j = x x^i y^j = x y^j x^i = y^j x x^i = y^j x^(i+1)$.
    - $x^i y^(j+1) = x^i y^j y = y^j x^i y = y^j y x^i = y^(j+1) x^i$.
  Since the elements of $G$ are of the form $x^i y^j$ then taking two elements $x^i y^j, x^(i') y^(j') in G$ we have $
    (x^i y^j) (x^i' y^j') &= x^i (y^j x^i') y^j'\
    &= x^i x^i' y^j y^j'\
    &= x^(i+i') y^(j+j')\
    &= x^(i'+i) y^(j'+j)\
    &= x^i' (x^i y^j') y^j\
    &= (x^i' y^j') (x^i y^j)
  $ thus $G$ is abelian.

  #qst[
    Deduce that $y x = x y^3$, $y^2 x = x y^2$, $y^3 x = x y$.
  ]

  We have that $y x in.not H$ since $y x = y^m => x = y^(m-1) in H$, $y x != x$ since $y x = x => y = e$, $y x != x y$ since $G$ is not abelian, and $y x != x y^2$ since if $y x = x y^2$ then $ x = y^(-1) x y^2 => x^2 = y^(-1) x y x y^2$, if $x^2 = y^2$ then $y^(-1) x y x = e => y^(-1) x y^3 = x$ which results in $y = e$ contradiction, if $x^2 = e$ then $y^(-1) x y x y^2 = e => (x y)^2 = e => y x y = x => y x = x y^3$ then $y = e$ contradiction. So the only element $y x$ can be is $x y^3$. $y x = x y^3 => y^2 x = y x y^(3) = x y^3 y^3 = x y^6 = x y^2 => y^3 x = y x y^2 = x y^3 y^2 = x y^5 = x y$.

  #qst[
    Suppose that $x^2 = e$, prove that $G$ is the Dihedral group $D_(8)$.
  ]

  If $x^2 = e$, then by taking the mapping $phi: G -> D_8$ such that $phi(x) = s$ and $phi(y) = r$ then we get that $phi$ is an isomorphism.

  #qst[
    Suppose that $x^2 = y^2$, dress the multiplication table of $G$ and verify it is a group.
  ]

  #align(center)[
    #grid(
      columns: (..(0.8cm,)*9),
      rows: (..(0.8cm,)*9),
      align: horizon + center,
      stroke: 0.2mm + black,
      gutter: (0.5mm, auto),
      inset: 1mm,
      fill: (x, y) => if (x == 0 or y == 0) { blue.opacify(-85%) },
      [$dot.c$], [$e$], [$y$], [$y^2$], [$y^3$], [$x$], [$x y$], [$x y^2$], [$x y^3$],
      [$e$], [$e$], [$y$], [$y^2$], [$y^3$], [$x$], [$x y$], [$x y^2$], [$x y^3$],
      [$y$], [$y$], [$y^2$], [$y^3$], [$e$], [$x y$], [$x y^2$], [$x y ^3$], [$x$],
      [$y^2$], [$y^2$], [$y^3$], [$e$], [$y$], [$x y^ 2$], [$x y^3$], [$x$], [$x y$],
      [$y^3$], [$y^3$], [$e$], [$y$], [$y^2$], [$x y^3$], [$x$], [$x y$], [$x y^2$],
      [$x$], [$x$], [$x y^3$], [$x y^2$], [$x y$], [$y^2$], [$y$], [$e$], [$y$],
      [$x y$], [$x y$], [$x$], [$x y^3$], [$x y^2$], [$y^3$], [$y^2$], [$y$], [$e$],
      [$x y^2$], [$x y^2$], [$x y$], [$x$], [$x y^3$], [$e$], [$y^3$], [$y^2$], [$y$],
      [$x y^3$], [$x y^3$], [$x y^2$], [$x y$], [$x$], [$y$], [$e$], [$y^3$], [$y^2$]
    )
  ]
  Which is indeed a group generated by $chevron.l x, y chevron.r$.

  #qst[
    Deduce there are exactly $2$ non-abelian groups of order $8$.
  ]
  The group will either be isomorphic to $D_8$ or $Q_8$.

  #exr[
    Let $Q_8$ be the quaternion group.
  ]
  Notice that $Q_8 = chevron.l x, y chevron.r$. To simplify the calculations, we use the formula that is easy to prove by induction $y^j x^i = x^i y^((-1)^i j)$ and the following lemma
  #lem(count: false)[
    Let $G = chevron.l S chevron.r$ be a group, and $cal(Z)(G)$ be its center. We have that $x in cal(Z)(G) <=> forall s in S, s x = x s$.
  ]
  #prf[
    $=>$ Trivial since $S subset G$. $arrow.l.double$ Suppose that $forall s in S, s x = x s$, let $y in G$ then $y = product_(i=1)^n s_i$ with $s_i in S$, then $y x = product_(i=1)^n s_i x = product_(i=1)^(n-1) s_i (s_n x) = product_(i=1)^(n-1) s_i x s_n = dots.c = x product_(i=1)^n s_i = x y$.
  ]

  #qst[
    Determine the center and commutator of $Q_8$.
  ]
  - The center $cal(Z)(Q_8)$: let $x^i y^j in cal(Z)(Q_8)$. We have $x x^i y^j = x^(i+1) y^j$ and $x^i y^j x = x^(i+1) y^(-j)$ so $j = -j mod 4 => 2j = 4k => j = 2k$ thus $j$ should be even. $y x^i y^j = x^i y^((-1)^i + j)$ and $x^i y^(j) y = x^i y^(j+1)$ thus $j + 1 = (-1)^i + j mod 4 => (-1)^i - 1 = 4k$ so necessarily $i = 0$. Thus we obtain that $cal(Z)(Q_8) = {e, y^2}$.
  - The commutator $[Q_8, Q_8]$:

  #qst[
    Proving that $ZZ_4 times ZZ_4$ and $ZZ_2 times Q_8$ are not isomorphic even though they have elements all of the same orders.
  ]
  Notice that in this case the order of an element $(x, y)$ is the same as the order of an element $(y, x)$. The tables below show the order of each element of the form $(x, y)$.

  #align(center)[
    #grid(
      columns: (1fr, 1fr),
      align: horizon, 
      [
        $ZZ_4 times ZZ_4$

        #grid(
          columns: (..(0.9cm,)*5),
          rows: (..(0.9cm,)*5),
          align: horizon + center,
          stroke: 0.2mm + black,
          gutter: (0.5mm, auto),
          inset: 2mm,
          fill: (x, y) => if (x == 0 or y == 0) { blue.opacify(-85%) },
          $dot.c$, $0$, $1$, $2$, $3$,
              $0$, $1$, $4$, $2$, $4$,
              $1$, $4$, $4$, $4$, $4$,
              $2$, $2$, $4$, $2$, $4$,
              $3$, $4$, $4$, $4$, $4$,
        )
      ],
      [
        $ZZ_2 times Q_8$

        #grid(
          columns: (..(0.9cm,)*3),
          rows: (..(0.9cm,)*9),
          align: horizon + center,
          stroke: 0.2mm + black,
          gutter: (0.5mm, auto),
          inset: 2mm,
          fill: (x, y) => if (x == 0 or y == 0) { blue.opacify(-85%) },
          $dot.c$, $0$, $1$,
              $e$, $1$, $2$,
              $y$, $4$, $4$,
            $y^2$, $2$, $2$,
            $y^3$, $4$, $4$,
              $x$, $4$, $4$,
            $x y$, $4$, $4$,
          $x y^2$, $4$, $4$,
          $x y^3$, $4$, $4$
        )
      ]
    )
  ]

  Thus, they both have $1$ element of order $1$, $3$ elements of order $2$ and $12$ elements of order $4$. Suppose that $ZZ_4 times ZZ_4$ is isomorphic to $ZZ_2 times Q_8$,

  #__cbox-count.update(0)
  #colbreak()
  #section(level: 1, [Series: Symmetric Groups.])
  #exr[
    Let $G$ be a non-abelian group with order $10$. Show that $G$ is isomorphic to $D_10$.
  ]
  It is easy to generalize, so we prove the following proposition.
  #thm(count: false)[
    Let $G$ be a non-abelian group with order $2p$, then $G$ is isomorphic to $D_(2p)$.
  ]

  #prf[
    We separate the proof into claims.
    - _Claim 1_: $exists r in G, o(y) = p$. Suppose by contradiction that there is no element of order $p$, then every element has order $2$, but this makes $G$ abelian, contradiction, thus there is $r in G$ such that $o(r) = p$. Take $H = chevron.l r chevron.r$.
    - _Claim 2_: $exists s in G \\ H, G = H union s H$. Consider $s in G \\ H$, we have that $card H = card s H = p$ and $H inter s H = emptyset$ (since if $H inter s H eq.not emptyset$ then $exists n, m in NN, s r^n = r^m => s = r^(m-n) in H$ which is a contradiction) thus $H inter s H = emptyset$, thus $H union s H subset G$ and $card (H union s H) = card G => G = H union s H$. 
    - _Claim 3_: $s^2 = e$. We have that $s^2 in.not s H$, since if it were then $s^2 = s z, z in H$ thus $s = z in H$ contradiction, therefore $s^2 in H$, thus $s^2$ has either order $1$ or $p$, if its order is $p$ then $s$ has order $s^(2p)$ thus $G$ is cyclic so abelian so it is necessarily $1$, thus $s^2 = e$.
    - _Claim 4_: $r s = s r^(-1)$. Through the same proof as the previous exercise we get that $r s = s r^(-1)$.
    Therefore, we have that $G$ is isomorphic to $D_(2p)$.
  ]

  #exr[

  ]

  #exr[
    Consider the permutation $
      sigma = mat(
        1, 2, 3, 4, 5, 6;
        6, 5, 4, 3, 1, 2;
      )
    $
  ]

  #qst[
    Computing $sigma^k$ for $k in NN$, and calculate the order of each $sigma^k$.
  ]

  $
    sigma^1 &= mat(
      1, 2, 3, 4, 5, 6;
      6, 5, 4, 3, 1, 2;
    ) #h(1cm)
    sigma^2 &= mat(
      1, 2, 3, 4, 5, 6;
      2, 1, 3, 4, 6, 5;
    )\

    sigma^3 &= mat(
      1, 2, 3, 4, 5, 6;
      5, 6, 4, 3, 2, 1;
    ) #h(1cm)
    sigma^4 &= mat(
      1, 2, 3, 4, 5, 6;
      1, 2, 3, 4, 5, 6;
    )\
  $

  We have that $sigma$ has order $4$, $sigma^2$ has order $2$ and $sigma^3 = sigma^(-1)$ which has order $4$.

  #qst[
    Find the cycles of $sigma$ and write it as a product of transpositions.
  ]
  We have that $(1 6 2 5)$ and $(3 4)$ are the cycles of $sigma$ thus $sigma = (1 6 2 5) (3 4)$. We use the fact that $(i_1 dots i_k) = (i_1 i_k) dots.c (i_1 i_2)$ then we have that $sigma = (1 5) (1 2) (1 6) (3 4)$.

  #qst[
    Find the parity of $sigma$ and the parity of each $sigma^k, k in ZZ$.
  ]
  The parity of $sigma$ is even since it has $4$ transpositions, thus $sigma^k$ would have parity even too, since $sigma^k = ((1 5) (1 2) (1 6) (3 4))^k$, which would have $4 k$ transpositions.

  #exr[ ]

  #qst[
    Prove $(1 space 2 dots n)^(-1) = (n space n - 1 dots 1)$.
  ]

  $
    (1 space 2 dots n) dot.c (n space n-1 dots 1) &= (1)
  $

  #qst[
    What is the order of an $l$-cycle, and the order of products of disjoint cycles of lengths $l_1, dots, l_s$.
  ]
]
